# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='videos/')),
                ('thumbnail', models.ImageField(max_length=255, upload_to='thumbnails/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('private', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
