# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoupload',
            old_name='private',
            new_name='is_private',
        ),
    ]
